from datetime import date, timedelta

numPages = 0

_weekdayDict = {
        0 : "Monday",
        1 : "Tuesday",
        2 : "Wednesday",
        3 : "Thursday",
        4 : "Friday",
        5 : "Saturday",
        6 : "Sunday"
        }

_monthDict = {
        1 : "January",
        2 : "Februrary",
        3 : "March",
        4 : "April",
        5 : "May",
        6 : "June",
        7 : "July",
        8 : "August",
        9 : "September",
        10: "October",
        11: "November",
        12: "December"
        }

# Page Functions
def _num_suffix(num):
    if num % 10 == 1:
        return "st"
    if num % 10 == 2:
        return "nd"
    if num % 10 == 3:
        return "rd"
    return "th"

def paper_width(depth):
    return "5.5in" if depth % 2 == 0 else "8.5in" 

def paper_height(depth):
    return "8.5in" if depth % 2 == 0 else "11.5in" 

def print_blank(output):
    global numPages
    numPages += 1
    output.write("\\begin{tikzpicture}\n"
            + "\t% Framing Nodes\n"
            + "\t\\node at (0,0) {};\n"
            + "\t\\node at (8.5, 11) {};\n"
            + "\\end{tikzpicture}\n")

def print_title(output, title, subtitle, ownerName, phoneNumber, address1, address2, city, state, country, zipCode):
    global numPages
    numPages += 3
    output.write("\\begin{tikzpicture}[\n"
            + "\tinner sep=3 pt,\n"
            + "\ttitle/.style={%\n"
            + "\t\tanchor = south,\n"
            + "\t\tnode font=\\Huge,\n"
            + "\t\talign=center,\n"
            + "\t},\n"
            + "\tsubtitle/.style={%\n"
            + "\t\tanchor = south,\n"
            + "\t\tnode font=\\huge,\n"
            + "\t\talign=center,\n"
            + "\t},\n"
            + "\tcontactinfo/.style={%\n"
            + "\t\tanchor = north west,\n"
            + "\t\tnode font=\\normalsize,\n"
            + "\t\talign=left,\n"
            + "\t},\n"
            + "\tyscale = -1]\n"
            + "\t% Framing Nodes\n"
            + "\t\\node at (0,0) {};\n"
            + "\t\\node at (8.5, 11) {};\n"
            + "\n"
            + "\t% Title and Subtitle\n"
            + f"\t\\node at (4.25,4) [title] {{{title}}};\n"
            + f"\t\\node at (4.25, 5) [subtitle] {{{subtitle}}};\n"
            + "\n"
            + "\t% Contact Info\n"
            + "\t\\draw (1.25,6) rectangle (7.25,8.5);\n"
            + "\t\\foreach \\i in {6.5, 7, ..., 8}{\n"
            + "\t\t\\draw [thin, gray] (1.25, \\i) -- (7.25, \\i);\n"
            + "\t}\n"
            + "\n"
            + f"\t\\node at (1.5, 6) [contactinfo] {{{ownerName}}};\n"
            + f"\t\\node at (1.5, 6.5) [contactinfo] {{{phoneNumber}}};\n"
            + f"\t\\node at (1.5, 7) [contactinfo] {{{address1}}};\n"
            + f"\t\\node at (1.5, 7.5) [contactinfo] {{{address2}}};\n"
            + f"\t\\node at (1.5, 8) [contactinfo] {{{city}, {state} {zipCode} {country}}};\n"
            + "\n"
            + "\\end{tikzpicture}\n"
            + "\\begin{tikzpicture}[\n"
            + "\tyscale = -1]\n"
            + "\t% Framing Nodes\n"
            + "\t\\node at (0,0) {};\n"
            + "\t\\node at (8.5, 11) {};\n"
            + "\\end{tikzpicture}\n"
            + "\\begin{tikzpicture}[\n"
            + "\tyscale = -1]\n"
            + "\t% Framing Nodes\n"
            + "\t\\node at (0,0) {};\n"
            + "\t\\node at (8.5, 11) {};\n"
            + "\n"
            + "\\end{tikzpicture}\n")

def print_year(output, currDate):
    pass

def print_quarter(output, currDate):
    pass

def print_month(output, currDate):
    global numPages
    numPages += 4
    output.write("\\begin{tikzpicture}[\n"
            + "\tyscale = -1]\n"
            + "\t% Framing Nodes\n"
            + "\t\\node at (0,0) {};\n"
            + "\t\\node at (8.5,11) {};\n"
            + "\\end{tikzpicture}\n"
            + "\\begin{tikzpicture}[\n"
            + "\tyscale = -1]\n"
            + "\t% Framing Nodes\n"
            + "\t\\node at (0,0) {};\n"
            + "\t\\node at (8.5,11) {};\n"
            + "\\end{tikzpicture}\n")

def print_week(output, currDate):
    global numPages
    numPages += 2
    output.write("\\begin{tikzpicture}[\n"
            + "\tinner sep=3 pt,\n"
            + "\ttitle/.style={%\n"
            + "\t\tnode font=\\normalsize,\n"
            + "\t},\n"
            + "\tsubtitle/.style={%\n"
            + "\t\tanchor = north,\n"
            + "\t\tnode font=\\normalsize,\n"
            + "\t},\n"
            + "\tday/.style={%\n"
            + "\t\tanchor = west,\n"
            + "\t\tnode font=\\small,\n"
            + "\t},\n"
            + "\thabitdate/.style={%\n"
            + "\t\tanchor = north west,\n"
            + "\t\tnode font = \\scriptsize,\n"
            + "\t},\n"
            + "\thabit/.style={\n"
            + "\t\tanchor = north west,\n"
            + "\t\tnode font = \\scriptsize,\n"
            + "\t},\n"
            + "\tyscale = -1]\n"
            + "\t% Framing Nodes\n"
            + "\t\\node at (0,0) {};\n"
            + "\t\\node at (8.5,11) {}; % each unit is 1/2 inch\n"
            + "\n"
            + "\t% ToDo list lines\n"
            + "\t\\foreach \\i in {1.5, 2, ..., 6}{\n"
            + "\t\t\\draw [gray, thin] (1, \\i) -- (4, \\i);\n"
            + "\t}\n"
            + "\t% Check Boxes\n"
            + "\t\\foreach \\i in {1, 1.5, ..., 6}{\n"
            + "\t\t\\draw (0.6,\\i+.1) rectangle (0.9,\\i+0.4);\n"
            + "\t}\n"
            + "\n"
            + "\t% Meal Plan Separator\n"
            + "\t\\draw [thick] (0.5, 6.5) -- (8, 6.5);\n"
            + "\n"
            + "\t% Meal Plan Day Lines\n"
            + "\t\\foreach \\i in {7, 7.5, ..., 10}{\n"
            + "\t\t\\draw (0.5, \\i) -- (4.25, \\i);\n"
            + "\t}\n"
            + "\t\\node [subtitle] at (2.3, 6.5) {Meal Plan};\n"
            + "\t\\node [day] at (0.5, 7.25) {M:};\n"
            + "\t\\node [day] at (0.5, 7.75) {T:};\n"
            + "\t\\node [day] at (0.45, 8.25) {W:};\n"
            + "\t\\node [day] at (0.5, 8.75) {R:};\n"
            + "\t\\node [day] at (0.5, 9.25) {F:};\n"
            + "\t\\node [day] at (0.5, 9.75) {S:};\n"
            + "\t\\node [day] at (0.5, 10.25) {S:};\n"
            + "\n"
            + "\t% Notes section\n"
            + "\t\\foreach \\i in {1, 1.306, ..., 6.5}{\n"
            + "\t\t\\draw [gray, thin] (4.25, \\i) -- (8, \\i);\n"
            + "\t}\n"
            + "\n"
            + "\t% Habits Section\n"
            + "\t% Vertical\n"
            + "\t\\foreach \\i in {6, 6.25, ..., 8}{\n"
            + "\t\t\\draw  [gray, thin] (\\i, 6.5) -- (\\i, 10.5);\n"
            + "\t}\n"
            + "\t\\draw (6, 6.5) -- (6, 10.5);\n"
            + "\n"
            + "\t% Horizontal\n"
            + "\t\\foreach \\i in {7, 7.35, ..., 10.5}{\n"
            + "\t\t\\draw (4.25, \\i) -- (8, \\i);\n"
            + "\t}\n"
            + "\t\\draw [thick] (4.25, 7) -- (8,7);\n"
            + "\n"
            + "\t% Text\n"
            + "\t\\node [anchor=north west] at (4.25, 6.5) {Habit};\n"
            + "\t\\node [habitdate] at (5.88, 6.55) {M};\n"
            + "\t\\node [habitdate] at (6.16, 6.55) {T};\n"
            + "\t\\node [habitdate] at (6.37, 6.55) {W};\n"
            + "\t\\node [habitdate] at (6.66, 6.55) {R};\n"
            + "\t\\node [habitdate] at (6.92, 6.55) {F};\n"
            + "\t\\node [habitdate] at (7.18, 6.55) {S};\n"
            + "\t\\node [habitdate] at (7.43, 6.55) {S};\n"
            + "\t\\node [habitdate] at (7.64, 6.51) {\\#};\n"
            + "\n"
            + "\t\\node [habit] at (4.25, 7) {Exercise};\n"
            + "\t\\node [habit] at (4.25, 7.35) {Sleep 11-8};\n"
            + "\t\\node [habit] at (4.25, 7.7) {Pets};\n"
            + "\t\\node [habit] at (4.25, 8.05) {Read};\n"
            + "\t\\node [habit] at (4.25, 8.4) {Meditate};\n"
            + "\t\\node [habit] at (4.25, 8.75) {Vit./Meds.};\n"
            + "\t\\node [habit] at (4.25, 9.1) {Eat Healthy};\n"
            + "\n"
            + "\t\\node [habit] at (7.67, 7) {5};\n"
            + "\t\\node [habit] at (7.67, 7.35) {7};\n"
            + "\t\\node [habit] at (7.67, 7.7) {7};\n"
            + "\t\\node [habit] at (7.67, 8.05) {7};\n"
            + "\t\\node [habit] at (7.67, 8.4) {7};\n"
            + "\t\\node [habit] at (7.67, 8.75) {7};\n"
            + "\t\\node [habit] at (7.67, 9.1) {6};\n"
            + "\n"
            + "\t% Vertical Split\n"
            + "\t\\draw [thick] (4.25,1) -- (4.25, 10.5);\n"
            + "\n"
            + "\t% Date / Title and Border Lines\n"
            + f"\t\\node at (0.4,0.5) [title] [anchor=north west] {{ Week of {_monthDict[currDate.month]} {currDate.day}{_num_suffix(currDate.day)}"                                                   
                + f" - {_monthDict[(currDate + timedelta(days=6)).month]+' ' if (currDate + timedelta(days=6)).month != currDate.month else ''}"
                + f"{(currDate + timedelta(days=6)).day}{_num_suffix((currDate + timedelta(days=6)).day)}, {(currDate + timedelta(days=6)).year}}};\n"
            + "\t\\draw [thick] (0.5,1) -- (8,1);\n"
            + "\t\\draw [thick] (0.5, 10.5) -- (8, 10.5);\n"
            + "\t\\draw [thick] (0.5, 1) -- (0.5, 10.5);\n"
            + "\t\\draw [thick] (8, 1) -- (8, 10.5);\n"
            + "\n"
            + "\\end{tikzpicture}\n"
            + "\t\\begin{tikzpicture}[\n"
            + "\tinner sep=3 pt,\n"
            + "\ttitle/.style={%\n"
            + "\t\tnode font=\\normalsize,\n"
            + "\t},\n"
            + "\tday/.style={%\n"
            + "\t\tanchor=west,\n"
            + "\t\tnode font=\\footnotesize,\n"
            + "\t},\n"
            + "\tdate/.style={%\n"
            + "\t\tanchor = east,\n"
            + "\t\tnode font=\\tiny,\n"
            + "\t\tcolor=gray,\n"
            + "\t},\n"
            + "\tyscale = -1]\n"
            + "\t% Framing Nodes\n"
            + "\t\\node at (0,0) {};\n"
            + "\t\\node at (8.5,11) {};\n"
            + "\n"
            + "\t% Minor Horizontal Lines\n"
            + "\t\\foreach \\i in {1.5, 1.85417, ..., 5.5}{\n"
            + "\t\t\\draw [gray, thin] (0.75, \\i) -- (2.75, \\i);\n"
            + "\t\t\\draw [gray, thin] (3.25, \\i) -- (5.25, \\i);\n"
            + "\t\t\\draw [gray, thin] (5.75, \\i) -- (7.75, \\i);\n"
            + "\t}\n"
            + "\n"
            + "\t\\foreach \\i in {6.25, 6.60417, ..., 10.5}{\n"
            + "\t\t\\draw [gray, thin] (0.75, \\i) -- (2.75, \\i);\n"
            + "\t\t\\draw [gray, thin] (3.25, \\i) -- (5.25, \\i);\n"
            + "\t}\n"
            + "\n"
            + "\t\\foreach \\i in {6.25, 6.60417, ..., 8}{\n"
            + "\t\t\\draw [gray, thin] (5.75, \\i) -- (7.75, \\i);\n"
            + "\t}\n"
            + "\n"
            + "\t\\foreach \\i in {8.72917, 9.083333336, ..., 10.5}{\n"
            + "\t\t\\draw [gray, thin] (5.75, \\i) -- (7.75, \\i);\n"
            + "\t}\n"
            + "\n"
            + "\n"
            + "\n"
            + "\t% Date / Title and Border Lines\n"
            + "\t\\node at (0.5,0.4) [title] [anchor=north west] {Events, Appointments, and Due Dates};\n"
            + "\t\\draw [thick] (0.5,1) -- (8,1);\n"
            + "\t\\draw [thick] (0.5, 10.5) -- (8, 10.5);\n"
            + "\t\\draw [thick] (0.5, 1) -- (0.5, 10.5);\n"
            + "\t\\draw [thick] (8, 1) -- (8, 10.5);\n"
            + "\t\\draw [thick] (0.5, 5.75) -- (8, 5.75);\n"
            + "\t\\draw [thick] (5.5, 8) -- (8, 8);\n"
            + "\n"
            + "\t% Major Horizontal Lines\n"
            + "\t\\draw (0.5, 1.5) -- (8, 1.5);\n"
            + "\t\\draw (0.5, 6.25) -- (8, 6.25);\n"
            + "\t\\draw (5.5, 8.5) -- (8, 8.5);\n"
            + "\n"
            + "\t% Days / Dates\n"
            + "\t\\node [day] at (0.5, 1.28) {Monday};\n"
            + "\t\\node [day] at (3, 1.28) {Tuesday};\n"
            + "\t\\node [day] at (5.5, 1.28) {Wednesday};\n"
            + "\t\\node [day] at (0.5, 6.03) {Thursday};\n"
            + "\t\\node [day] at (3, 6.03) {Friday};\n"
            + "\t\\node [day] at (5.5, 6.03) {Saturday};\n"
            + "\t\\node [day] at (5.5, 8.28) {Sunday};\n"
            + "\n"
            + f"\t\\node [date] at (3, 1.3) {{{currDate.strftime('%m/%d')}}};\n"
            + f"\t\\node [date] at (5.5, 1.3) {{{(currDate + timedelta(days=1)).strftime('%m/%d')}}};\n"
            + f"\t\\node [date] at (8, 1.3) {{{(currDate + timedelta(days=2)).strftime('%m/%d')}}};\n"
            + f"\t\\node [date] at (3, 6.05) {{{(currDate + timedelta(days=3)).strftime('%m/%d')}}};\n"
            + f"\t\\node [date] at (5.5, 6.05) {{{(currDate + timedelta(days=4)).strftime('%m/%d')}}};\n"
            + f"\t\\node [date] at (8, 6.05) {{{(currDate + timedelta(days=5)).strftime('%m/%d')}}};\n"
            + f"\t\\node [date] at (8, 8.3) {{{(currDate + timedelta(days=6)).strftime('%m/%d')}}};\n"
            + "\n"
            + "\t% Vertical Lines\n"
            + "\t\\foreach \\i in {0.5, 3, ..., 8}{\n"
            + "\t\t\\draw [thick] (\\i, 1) -- (\\i, 10.5);\n"
            + "\t}\n"
            + "\\end{tikzpicture}\n")

def print_day(output, currDate):
    global numPages
    numPages += 2
    output.write("\\begin{tikzpicture}[\n"
            + "\tinner sep=3 pt,\n"
            + "\ttitle/.style={%\n"
            + "\t\tnode font=\\large,\n"
            + "\t},\n"
            + "\thournumber/.style={%\n"
            + "\t\tanchor = west,\n"
            + "\t\tnode font=\\small, \n"
            + "\t},\n"
            + "\tminutenumber/.style={%\n"
            + "\t\tanchor = west,\n"
            + "\t\tnode font=\\tiny, \n"
            + "\t\tcolor=gray,\n"
            + "\t},\n"
            + "\tyscale = -1]\n"
            + "\t% Framing Nodes\n"
            + "\t\\node at (0,0) {};\n"
            + "\t\\node at (8.5,11) {}; % each unit is 1/2 an inch\n"
            + "\t\n"
            + "\t% Date / Title and Border Lines\n"
            + f"\t\\node at (0.4,0.47) [title] [anchor=north west] {{{_weekdayDict[currDate.weekday()]}, {_monthDict[currDate.month]} {currDate.day}{_num_suffix(currDate.day)} {currDate.year}}};\n"
            + "\t\\draw [thick] (0.5,1) -- (8,1);\n"
            + "\t\\draw [thick] (0.5, 10.5) -- (8, 10.5);\n"
            + "\t\\draw [thick] (0.5, 1) -- (0.5, 10.5);\n"
            + "\t\\draw [thick] (8, 1) -- (8, 10.5);\n"
            + "\n"
            + "\t% Hour Numbers\n"
            + "\t\\foreach \\i in {0, 1, ..., 11}{\n"
            + "\t\t\\node [hournumber] at (0.45, \\i*9.5/12 + 1.2) {\\i};\n"
            + "\t}\n"
            + "\t\n"
            + "\t% Minute Numbers\n"
            + "\t\\foreach \\i in {0, 1, ..., 11}{\n"
            + "\t\t\\node [minutenumber] at (0.5, \\i*9.5/12 + 1.6) {:30};\n"
            + "\t}\n"
            + "\n"
            + "\t% Vertical Lines\n"
            + "\t\\draw (1,1) -- (1, 10.5);\n"
            + "\t\\foreach \\i in {1, 3.3333, ..., 8}{\n"
            + "\t\t\\draw (\\i, 1) -- (\\i, 10.5);\n"
            + "\t}\n"
            + "\n"
            + "\t% Minor Horizontal Lines\n"
            + "\t\\foreach \\i in {0.5, 1.5, ..., 11.5}{\n"
            + "\t\t\\draw [gray, thin] (1, \\i*9.5/12 + 1) -- (8, \\i*9.5/12 + 1);\n"
            + "\t}\n"
            + "\n"
            + "\t% Major Horizontal Lines\n"
            + "\t\\foreach \\i in {0, 1, ..., 11}{\n"
            + "\t\t\\draw (0.5,\\i*9.5/12 + 1) -- (8, \\i*9.5/12 + 1);\n"
            + "\t}\n"
            + "\t\n"
            + "\\end{tikzpicture}\n"
            + "\\begin{tikzpicture}[\n"
            + "\tinner sep=3 pt,\n"
            + "\ttitle/.style={%\n"
            + "\t\tnode font=\\Large,\n"
            + "\t},\n"
            + "\thournumber/.style={%\n"
            + "\t\tanchor=west,\n"
            + "\t\tnode font=\\small, \n"
            + "\t},\n"
            + "\tminutenumber/.style={%\n"
            + "\t\tanchor = west,\n"
            + "\t\tnode font=\\tiny, \n"
            + "\t\tcolor=gray,\n"
            + "\t},\n"
            + "\tyscale = -1]\n"
            + "\t% Framing Nodes\n"
            + "\t\\node at (0,0) {};\n"
            + "\t\\node at (8.5,11) {}; % each unit is 1/2 an inch\n"
            + "\t\n"
            + "\t% Date / Title and Border Lines\n"
            + "\t\\draw [thick] (0.5,1) -- (8,1);\n"
            + "\t\\draw [thick] (0.5, 10.5) -- (8, 10.5);\n"
            + "\t\\draw [thick] (0.5, 1) -- (0.5, 10.5);\n"
            + "\t\\draw [thick] (8, 1) -- (8, 10.5);\n"
            + "\n"
            + "\t% Hour Numbers\n"
            + "\t\\foreach \\i [evaluate=\\i as \\n using int(\\i+12)] in {0, 1, ..., 11}{\n"
            + "\t\t\\node [hournumber] at (0.45, \\i*9.5/12 + 1.2) {\\n};\n"
            + "\t}\n"
            + "\t\n"
            + "\t% Minute Numbers\n"
            + "\t\\foreach \\i in {0, 1, ..., 11}{\n"
            + "\t\t\\node [minutenumber] at (0.5, \\i*9.5/12 + 1.6) {:30};\n"
            + "\t}\n"
            + "\n"
            + "\t% Vertical Lines\n"
            + "\t\\draw (1,1) -- (1, 10.5);\n"
            + "\t\\foreach \\i in {1, 3.3333, ..., 8}{\n"
            + "\t\t\\draw (\\i, 1) -- (\\i, 10.5);\n"
            + "\t}\n"
            + "\n"
            + "\t% Minor Horizontal Lines\n"
            + "\t\\foreach \\i in {0.5, 1.5, ..., 11.5}{\n"
            + "\t\t\\draw [gray, thin] (1, \\i*9.5/12 + 1) -- (8, \\i*9.5/12 + 1);\n"
            + "\t}\n"
            + "\n"
            + "\t% Major Horizontal Lines\n"
            + "\t\\foreach \\i in {0, 1, ..., 11}{\n"
            + "\t\t\\draw (0.5,\\i*9.5/12 + 1) -- (8, \\i*9.5/12 + 1);\n"
            + "\t}\n"
            + "\t\n"
            + "\\end{tikzpicture}\n")

def print_endpages(output, minEndpages, signatureLen):
    global numPages
    endpageCount = 0
    while endpageCount < minEndpages or numPages % signatureLen != 0:
        endpageCount += 1
        numPages += 1
        output.write("\t\\begin{tikzpicture}[\n"
                + "\t\tinner sep=3 pt,\n"
                + "\t\ttitle/.style={%\n"
                + "\t\t\tnode font=\\normalsize,\n"
                + "\t\t},\n"
                + "\t\tday/.style={%\n"
                + "\t\t\tanchor=west,\n"
                + "\t\t\tnode font=\\footnotesize, \n"
                + "\t\t},\n"
                + "\t\tdate/.style={%\n"
                + "\t\t\tanchor = east,\n"
                + "\t\t\tnode font=\\tiny, \n"
                + "\t\t\tcolor=gray,\n"
                + "\t\t},\n"
                + "\t\tyscale = -1]\n"
                + "\t\t% Framing Nodes\n"
                + "\t\t\\node at (0,0) {};\n"
                + "\t\t\\node at (8.5,11) {};\n"
                + "\t\t\n"
                + "\t\t% Minor Horizontal Lines\n"
                + "\t\t\\foreach \i in {1, 1.5, ..., 10.5}{\n"
                + "\t\t\t\\draw [gray, thin] (0.5, \i) -- (8, \i);\n"
                + "\t\t}\n"
                + "\t\t% Date / Title and Border Lines\n"
                + "\t\t\\node at (0.5,0.5) [title] [anchor=north west] {Notes and Future Dates};\n"
                + "\t\\end{tikzpicture}\n")
